name: ABI Artifacts

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-abi:
    name: Build and upload ABI JSON
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Generate ABI
        run: make abi FORGE=forge

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: abi-json
          path: |
            src/abi/Aggregator_ABI.json
            src/abi/Client_ABI.json
