name: ABI Artifacts

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-abi:
    name: Build and upload ABI JSON
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Setup git user (for forge install)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install Solidity dependencies
        run: |
          forge install openzeppelin/openzeppelin-contracts@v5.4.0 foundry-rs/forge-std@v1.9.7

      - name: Generate ABI
        run: make abi FORGE=forge

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: abi-json
          path: |
            src/abi/Aggregator_ABI.json
            src/abi/Client_ABI.json
