name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  solidity:
    name: Solidity (Foundry)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Cache Solidity libs
        uses: actions/cache@v4
        with:
          path: lib
          key: lib-${{ runner.os }}-${{ hashFiles('foundry.toml') }}
          restore-keys: |
            lib-${{ runner.os }}-

      - name: Setup git user (for forge install)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install Solidity dependencies
        run: |
          forge install openzeppelin/openzeppelin-contracts@v5.4.0 foundry-rs/forge-std@v1.9.7

      - name: Build contracts
        run: make build FORGE=forge

      - name: Run Solidity tests
        run: make test-sol FORGE=forge

  python:
    name: Python (tests)
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python tests
        env:
          PYTHONPATH: src
          TF_CPP_MIN_LOG_LEVEL: '2'
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: '1'
        run: make test-py
